const records = [
    { rollno: "1", name: "RAJESH KUMAR", email: "1@iitk.ac.in" },
    { rollno: "2", name: "AMARDEEP SINGH TOMAR", email: "2@iitk.ac.in" },
    { rollno: "3", name: "AYUSHI SULLEREY", email: "3@iitk.ac.in" },
    { rollno: "4", name: "ALOK RAJ", email: "4@iitk.ac.in" },
    { rollno: "5", name: "MD MANZAR", email: "5@iitk.ac.in" },
    { rollno: "6", name: "MUDIT SINHA", email: "6@iitk.ac.in" },
    { rollno: "7", name: "RAHUL GARG", email: "7@iitk.ac.in" },
    { rollno: "8", name: "ANTRIKSH SAREEN", email: "8@iitk.ac.in" },
    { rollno: "9", name: "KISHLAY KUMAR", email: "9@iitk.ac.in" },
    { rollno: "10", name: "ROHIT KUMAR", email: "10@iitk.ac.in" },
    { rollno: "11", name: "CHIRAG BHARATBHAI", email: "11@iitk.ac.in" },
    { rollno: "12", name: "ANKIT SHRIVASTAVA", email: "12@iitk.ac.in" },
    { rollno: "13", name: "PRAVEEN NAWAL", email: "13@iitk.ac.in" },
    { rollno: "14", name: "JUHI CHANDRA", email: "14@iitk.ac.in" },
    { rollno: "15", name: "ANIL KUMAR", email: "15@iitk.ac.in" },
    { rollno: "16", name: "MAHESH DADHICH", email: "16@iitk.ac.in" },
    { rollno: "17", name: "PRAKHAR AGARWAL", email: "17@iitk.ac.in" },
    { rollno: "18", name: "AJAY KUMAR", email: "18@iitk.ac.in" },
    { rollno: "19", name: "DEEPANSHU KUMAWAT", email: "19@iitk.ac.in" },
    { rollno: "20", name: "REENA PANWAR", email: "20@iitk.ac.in" },
    { rollno: "21", name: "GOVIND SINGH", email: "21@iitk.ac.in" },
    { rollno: "22", name: "ASHISH BALOTIYA", email: "22@iitk.ac.in" },
    { rollno: "23", name: "PANDYA AMAN HITESH", email: "23@iitk.ac.in" },
    { rollno: "24", name: "NIDHI SAHU", email: "24@iitk.ac.in" },
    { rollno: "25", name: "SANDEEP KUMAR GUPTA", email: "25@iitk.ac.in" },
    { rollno: "26", name: "IFFAT SIDDIQUI", email: "26@iitk.ac.in" },
    { rollno: "27", name: "DUMALA SHASHANKJI", email: "27@iitk.ac.in" },
    { rollno: "28", name: "VIBHA MISHRA", email: "28@iitk.ac.in" },
    { rollno: "29", name: "SHANIKA TRIPATHI", email: "29@iitk.ac.in" },
    { rollno: "30", name: "SARIKA KASHYAP", email: "30@iitk.ac.in" },
    { rollno: "31", name: "RISHABH RAWAT", email: "31@iitk.ac.in" },
    { rollno: "32", name: "AKASH AWASTHI", email: "32@iitk.ac.in" },
    { rollno: "33", name: "SHRUTI SHUKLA", email: "33@iitk.ac.in" },
    { rollno: "34", name: "SHIVANI JAISWAL", email: "34@iitk.ac.in" },
    { rollno: "35", name: "TANISH BAJPAI", email: "35@iitk.ac.in" },
    { rollno: "36", name: "MILIND SINGH", email: "36@iitk.ac.in" },
    { rollno: "37", name: "PRAGATI KATIYAR", email: "37@iitk.ac.in" },
    { rollno: "38", name: "SHASHVI MISHRA", email: "38@iitk.ac.in" },
    { rollno: "39", name: "VAIBHAV MISHRA", email: "39@iitk.ac.in" },
    { rollno: "40", name: "AMAN ROHILA", email: "40@iitk.ac.in" },
];


export default function getData(){
    return records;
}